# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='team.png', upload_to='teams/')),
                ('position', models.CharField(blank=True, help_text='Position of the team eg. CEO', max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, default=' ', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, default=' ', help_text='Please enter only the user name eg. in/mawy7 ', max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_current_lead', models.BooleanField(default=False)),
                ('is_past_lead', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='team_name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
