# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(default='', help_text='The event link.'),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
