# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180424_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.CharField(default='', help_text='The event link.', max_length=100),
        ),
    ]
