# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180424_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_url',
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Link to Facebook Photo Ablum'),
        ),
        migrations.AddField(
            model_name='event',
            name='register_url',
            field=models.URLField(blank=True, default='', help_text='Link to Google Photo Ablum'),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Link to Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='mm/dd/yyyy', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='mm/dd/yyyy', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='twitter_url',
            field=models.URLField(blank=True, default='', help_text='Link to Flick Photo Ablum'),
        ),
    ]
