# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180427_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Link to Facebook Page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_url',
            field=models.URLField(blank=True, default='', help_text='Link for Registrations, if any'),
        ),
        migrations.AlterField(
            model_name='event',
            name='twitter_url',
            field=models.URLField(blank=True, default='', help_text='Link to Twitter Handle Ablum'),
        ),
    ]
