# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-27 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180427_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='twitter_url',
            field=models.URLField(blank=True, default='', help_text='Link to Twitter Handle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Link to Event Website'),
        ),
    ]
