# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-11 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
