# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171011_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url',
            field=models.URLField(default='', help_text='Link to Photo Ablum'),
        ),
    ]
