# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_album_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='facebook_url',
            field=models.URLField(default='', help_text='Link to Facebook Photo Ablum'),
        ),
        migrations.AddField(
            model_name='album',
            name='flickr_url',
            field=models.URLField(default='', help_text='Link to Flick Photo Ablum'),
        ),
        migrations.AddField(
            model_name='album',
            name='googlephotos_url',
            field=models.URLField(default='', help_text='Link to Google Photo Ablum'),
        ),
    ]
