# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180302_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Link to Facebook Photo Ablum'),
        ),
        migrations.AlterField(
            model_name='album',
            name='flickr_url',
            field=models.URLField(blank=True, default='', help_text='Link to Flick Photo Ablum'),
        ),
        migrations.AlterField(
            model_name='album',
            name='googlephotos_url',
            field=models.URLField(blank=True, default='', help_text='Link to Google Photo Ablum'),
        ),
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Link to Photo Ablum'),
        ),
    ]
