# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180424_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_link',
            field=models.URLField(blank=True, default='', help_text='Link to Flick Photo Ablum'),
        ),
    ]
