# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_album_album_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_link',
            field=models.URLField(help_text='Link to Photo Ablum'),
        ),
    ]
