# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20191025_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='Link to Facebook Page'),
        ),
        migrations.AddField(
            model_name='event',
            name='register_url',
            field=models.URLField(blank=True, default='', help_text='Link for Registrations, if any'),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_url',
            field=models.URLField(blank=True, default='', help_text='Link to Twitter Handle'),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Link to Event Website'),
        ),
    ]
