# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 19:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('profile_image', models.ImageField(default='team.png', upload_to='team/')),
                ('full_name', models.CharField(help_text='What is the name of team member', max_length=50)),
                ('twitter_handle', models.CharField(default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('linkedin', models.CharField(default='', help_text='Please enter only the user name eg. in/mawy7 ', max_length=100, null=True)),
                ('position_held', models.CharField(default='', help_text='Please enter the position held ', max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
