# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_image', models.ImageField(default='team.png', upload_to='resources/article/')),
                ('article_source', models.CharField(max_length=200)),
                ('article_description', models.TextField(blank=True, default=' ', help_text='Please enter article description')),
                ('article_link', models.CharField(blank=True, default=' ', help_text='Please enter link', max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='article_title')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_image', models.ImageField(default='team.png', upload_to='resources/books/')),
                ('book_description', models.TextField(blank=True, default=' ', help_text='Please enter book description')),
                ('book_link', models.CharField(blank=True, default=' ', help_text='Please enter link', max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='book_title')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_image', models.ImageField(default='team.png', upload_to='resources/video/')),
                ('video_description', models.TextField(blank=True, default=' ', help_text='Please enter video description')),
                ('video_link', models.CharField(blank=True, default=' ', help_text='Please enter link', max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='video_title')),
            ],
        ),
    ]
