# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-11 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20200411_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_source',
            new_name='article_author',
        ),
    ]
