# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200411_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_author',
            field=models.CharField(blank=True, help_text='Please enter video source, this is where the video is gotten from', max_length=200, null=True),
        ),
    ]
