# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-11 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20200411_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_date',
            new_name='video_release_date',
        ),
    ]
