# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-11 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_book_read_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, default='', help_text='Please enter book description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_link',
            field=models.CharField(default='', help_text='Please enter link', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_book_link',
            field=models.CharField(default='', help_text='Please enter link', max_length=100, null=True),
        ),
    ]
