# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20200411_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_book_link',
            field=models.CharField(blank=True, default='', help_text='Please enter link', max_length=100, null=True),
        ),
    ]
