# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_auto_20200411_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_description',
            field=models.TextField(blank=True, default='', help_text='Please enter article description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_link',
            field=models.CharField(default='', help_text='Please enter link', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_link',
            field=models.CharField(blank=True, default='', help_text='Please enter link', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(default='', help_text='Please enter link', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.TextField(blank=True, default='', help_text='Please enter video description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.CharField(default='', help_text='Please enter link', max_length=100, null=True),
        ),
    ]
